# Project FORESIGHT

## Phase 2: Data Understanding

### Objective

Understand all datasets before cleaning and preprocessing.

In [1]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 1000)

print("Libraries imported successfully.")

Libraries imported successfully.

In [4]:
sales = pd.read_csv("../data/raw/sales_daily.csv")
sku = pd.read_csv("../data/raw/sku_master.csv")
calendar = pd.read_csv("../data/raw/calendar.csv")
inventory = pd.read_csv("../data/raw/inventory_snapshots.csv")

print("Datasets loaded successfully.")

Datasets loaded successfully.

In [5]:
print("Sales Shape:", sales.shape)
print("SKU Shape:", sku.shape)
print("Calendar Shape:", calendar.shape)
print("Inventory Shape:", inventory.shape)

Sales Shape: (73000, 6)
SKU Shape: (200, 6)
Calendar Shape: (365, 6)
Inventory Shape: (9600, 6)

In [6]:
sales.head()

         date  sku_id  units_sold  revenue  unit_price  promo_flag
0  2024-01-01  SKU001          16  3814.08      238.38           0
1  2024-01-01  SKU002           9   943.65      104.85           0
2  2024-01-01  SKU003          14  4658.92      332.78           0
3  2024-01-01  SKU004          11  2825.35      256.85           0
4  2024-01-01  SKU005          12   575.40       47.95           0

In [7]:
sku.head()

   sku_id    category subcategory launch_date  unit_cost  list_price
0  SKU001  Appliances     General  2023-01-01        173      238.38
1  SKU002   Furniture     General  2023-01-01         72      104.85
2  SKU003   Furniture     General  2023-01-01        183      332.78
3  SKU004   Furniture     General  2023-01-01        161      256.85
4  SKU005   Furniture     General  2023-01-01         33       47.95

In [8]:
inventory.head()

         date  sku_id  on_hand_units  on_order_units  lead_time_days  reorder_point
0  2024-01-01  SKU001            171              95              13             71
1  2024-01-01  SKU002             78              59               5             29
2  2024-01-01  SKU003            135              86              15             74
3  2024-01-01  SKU004            207              11              15             20
4  2024-01-01  SKU005            155              68               6             49

In [9]:
calendar.head()

         date  week  month  season  is_holiday promo_event
0  2024-01-01     1      1  Winter           0         NaN
1  2024-01-02     1      1  Winter           0         NaN
2  2024-01-03     1      1  Winter           0         NaN
3  2024-01-04     1      1  Winter           0         NaN
4  2024-01-05     1      1  Winter           0         NaN

In [10]:
sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 73000 entries, 0 to 72999
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        73000 non-null  str
 1   sku_id      73000 non-null  str
 2   units_sold  73000 non-null  int64
 3   revenue     73000 non-null  float64
 4   unit_price  73000 non-null  float64
 5   promo_flag  73000 non-null  int64
dtypes: float64(2), int64(2), str(2)
memory usage: 3.3 MB

In [11]:
sku.info()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   sku_id       200 non-null    str
 1   category     200 non-null    str
 2   subcategory  200 non-null    str
 3   launch_date  200 non-null    str
 4   unit_cost    200 non-null    int64
 5   list_price   200 non-null    float64
dtypes: float64(1), int64(1), str(4)
memory usage: 9.5 KB

In [12]:
calendar.info()

<class 'pandas.DataFrame'>
RangeIndex: 365 entries, 0 to 364
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         365 non-null    str
 1   week         365 non-null    int64
 2   month        365 non-null    int64
 3   season       365 non-null    str
 4   is_holiday   365 non-null    int64
 5   promo_event  8 non-null      str
dtypes: int64(3), str(3)
memory usage: 17.2 KB

In [13]:
inventory.info()

<class 'pandas.DataFrame'>
RangeIndex: 9600 entries, 0 to 9599
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   date            9600 non-null   str
 1   sku_id          9600 non-null   str
 2   on_hand_units   9600 non-null   int64
 3   on_order_units  9600 non-null   int64
 4   lead_time_days  9600 non-null   int64
 5   reorder_point   9600 non-null   int64
dtypes: int64(4), str(2)
memory usage: 450.1 KB

In [14]:
sales.columns

Index(['date', 'sku_id', 'units_sold', 'revenue', 'unit_price', 'promo_flag'], dtype='str')

In [15]:
sku.columns

Index(['sku_id', 'category', 'subcategory', 'launch_date', 'unit_cost', 'list_price'], dtype='str')

In [16]:
calendar.columns

Index(['date', 'week', 'month', 'season', 'is_holiday', 'promo_event'], dtype='str')

In [17]:
inventory.columns

Index(['date', 'sku_id', 'on_hand_units', 'on_order_units', 'lead_time_days', 'reorder_point'], dtype='str')

In [18]:
sales.isnull().sum()

date          0
sku_id        0
units_sold    0
revenue       0
unit_price    0
promo_flag    0
dtype: int64

In [19]:
sku.isnull().sum()

sku_id         0
category       0
subcategory    0
launch_date    0
unit_cost      0
list_price     0
dtype: int64

In [20]:
calendar.isnull().sum()

date             0
week             0
month            0
season           0
is_holiday       0
promo_event    357
dtype: int64

In [21]:
inventory.isnull().sum()

date              0
sku_id            0
on_hand_units     0
on_order_units    0
lead_time_days    0
reorder_point     0
dtype: int64

In [22]:
sales.duplicated().sum()

np.int64(0)

In [23]:
sku.duplicated().sum()

np.int64(0)

In [24]:
calendar.duplicated().sum()

np.int64(0)

In [25]:
inventory.duplicated().sum()

np.int64(0)

In [26]:
sales.describe()

         units_sold       revenue    unit_price    promo_flag
count  73000.000000  73000.000000  73000.000000  73000.000000
mean      11.901219   2078.379005    175.070134      0.079918
std        4.226451   1398.413197     95.518430      0.271168
min        0.000000      0.000000     14.980000      0.000000
25%        9.000000    951.800000     94.060000      0.000000
50%       12.000000   1799.560000    166.710000      0.000000
75%       15.000000   2961.340000    248.890000      0.000000
max       32.000000  10292.400000    381.200000      1.000000

In [27]:
inventory.describe()

       on_hand_units  on_order_units  lead_time_days  reorder_point
count    9600.000000     9600.000000     9600.000000    9600.000000
mean      158.729375       49.728437       11.956250      49.877292
std        81.126128       29.136575        5.489628      17.712634
min        20.000000        0.000000        3.000000      20.000000
25%        87.000000       24.000000        7.000000      35.000000
50%       159.000000       50.000000       12.000000      50.000000
75%       229.000000       75.000000       17.000000      65.000000
max       300.000000      100.000000       21.000000      80.000000

# Data Understanding Summary

## sales_daily.csv
- Rows:
- Columns:
- Main Key: sku_id
- Date Column: date
- Missing Values:
- Duplicate Rows:

## sku_master.csv
- Number of Products:
- Categories:
- Price Columns:

## calendar.csv
- Date Range:
- Holiday Information:
- Season Information:

## inventory_snapshots.csv
- Inventory Metrics:
- Lead Time:
- Reorder Point:

In [28]:
print(sales.columns.tolist())
print(sku.columns.tolist())
print(calendar.columns.tolist())
print(inventory.columns.tolist())

['date', 'sku_id', 'units_sold', 'revenue', 'unit_price', 'promo_flag']
['sku_id', 'category', 'subcategory', 'launch_date', 'unit_cost', 'list_price']
['date', 'week', 'month', 'season', 'is_holiday', 'promo_event']
['date', 'sku_id', 'on_hand_units', 'on_order_units', 'lead_time_days', 'reorder_point']