# Project FORESIGHT

## Phase 4: Data Cleaning

### Objective

Clean the master dataset by identifying and handling missing values, duplicates, incorrect data types, and inconsistent data.

In [4]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 1000)

print("Libraries imported successfully.")

Libraries imported successfully.

In [5]:
df = pd.read_csv("../data/processed/master_dataset.csv")

print("Dataset Loaded Successfully")

Dataset Loaded Successfully

C:\Users\user\AppData\Local\Temp\ipykernel_5104\1966429318.py:1: DtypeWarning: Columns (0: promo_event) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("../data/processed/master_dataset.csv")

In [6]:
print("Shape:", df.shape)

df.head()

Shape: (73000, 20)

         date  sku_id  units_sold  revenue  unit_price  promo_flag    category subcategory launch_date  unit_cost  list_price  week  month  season  is_holiday promo_event  on_hand_units  on_order_units  lead_time_days  reorder_point
0  2024-01-01  SKU001          16  3814.08      238.38           0  Appliances     General  2023-01-01        173      238.38     1      1  Winter           0         NaN          171.0            95.0            13.0           71.0
1  2024-01-01  SKU002           9   943.65      104.85           0   Furniture     General  2023-01-01         72      104.85     1      1  Winter           0         NaN           78.0            59.0             5.0           29.0
2  2024-01-01  SKU003          14  4658.92      332.78           0   Furniture     General  2023-01-01        183      332.78     1      1  Winter           0         NaN          135.0            86.0            15.0           74.0
3  2024-01-01  SKU004          11  2825.35      256.85           0   Furniture     General  2023-01-01        161      256.85     1      1  Winter           0         NaN          207.0            11.0            15.0           20.0
4  2024-01-01  SKU005          12   575.40       47.95           0   Furniture     General  2023-01-01         33       47.95     1      1  Winter           0         NaN          155.0            68.0             6.0           49.0

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 73000 entries, 0 to 72999
Data columns (total 20 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   date            73000 non-null  str
 1   sku_id          73000 non-null  str
 2   units_sold      73000 non-null  int64
 3   revenue         73000 non-null  float64
 4   unit_price      73000 non-null  float64
 5   promo_flag      73000 non-null  int64
 6   category        73000 non-null  str
 7   subcategory     73000 non-null  str
 8   launch_date     73000 non-null  str
 9   unit_cost       73000 non-null  int64
 10  list_price      73000 non-null  float64
 11  week            73000 non-null  int64
 12  month           73000 non-null  int64
 13  season          73000 non-null  str
 14  is_holiday      73000 non-null  int64
 15  promo_event     1600 non-null   str
 16  on_hand_units   9600 non-null   float64
 17  on_order_units  9600 non-null   float64
 18  lead_time_days  9600 non-null   float64
 19  reorder_point   9600 non-null   float64
dtypes: float64(7), int64(6), str(7)
memory usage: 11.1 MB

In [8]:
df.isnull().sum()

date                  0
sku_id                0
units_sold            0
revenue               0
unit_price            0
promo_flag            0
category              0
subcategory           0
launch_date           0
unit_cost             0
list_price            0
week                  0
month                 0
season                0
is_holiday            0
promo_event       71400
on_hand_units     63400
on_order_units    63400
lead_time_days    63400
reorder_point     63400
dtype: int64

In [9]:
missing = df.isnull().sum()

missing[missing > 0]

promo_event       71400
on_hand_units     63400
on_order_units    63400
lead_time_days    63400
reorder_point     63400
dtype: int64

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
df = df.drop_duplicates()

In [12]:
df.duplicated().sum()

np.int64(0)

In [13]:
df.dtypes

date                  str
sku_id                str
units_sold          int64
revenue           float64
unit_price        float64
promo_flag          int64
category              str
subcategory           str
launch_date           str
unit_cost           int64
list_price        float64
week                int64
month               int64
season                str
is_holiday          int64
promo_event           str
on_hand_units     float64
on_order_units    float64
lead_time_days    float64
reorder_point     float64
dtype: object

In [14]:
df["date"] = pd.to_datetime(df["date"])

In [15]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 73000 entries, 0 to 72999
Data columns (total 20 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   date            73000 non-null  datetime64[us]
 1   sku_id          73000 non-null  str
 2   units_sold      73000 non-null  int64
 3   revenue         73000 non-null  float64
 4   unit_price      73000 non-null  float64
 5   promo_flag      73000 non-null  int64
 6   category        73000 non-null  str
 7   subcategory     73000 non-null  str
 8   launch_date     73000 non-null  str
 9   unit_cost       73000 non-null  int64
 10  list_price      73000 non-null  float64
 11  week            73000 non-null  int64
 12  month           73000 non-null  int64
 13  season          73000 non-null  str
 14  is_holiday      73000 non-null  int64
 15  promo_event     1600 non-null   str
 16  on_hand_units   9600 non-null   float64
 17  on_order_units  9600 non-null   float64
 18  lead_time_days  9600 non-null   float64
 19  reorder_point   9600 non-null   float64
dtypes: datetime64[us](1), float64(7), int64(6), str(6)
memory usage: 11.1 MB

In [16]:
df.describe()

                      date    units_sold       revenue    unit_price    promo_flag     unit_cost    list_price          week         month    is_holiday  on_hand_units  on_order_units  lead_time_days  reorder_point
count                73000  73000.000000  73000.000000  73000.000000  73000.000000  73000.000000  73000.000000  73000.000000  73000.000000  73000.000000    9600.000000     9600.000000     9600.000000    9600.000000
mean   2024-07-01 00:00:00     11.901219   2078.379005    175.070134      0.079918    107.645000    176.484950     26.430137      6.498630      0.142466     158.729375       49.728437       11.956250      49.877292
min    2024-01-01 00:00:00      0.000000      0.000000     14.980000      0.000000     10.000000     16.640000      1.000000      1.000000      0.000000      20.000000        0.000000        3.000000      20.000000
25%    2024-04-01 00:00:00      9.000000    951.800000     94.060000      0.000000     57.750000     94.780000     13.000000      4.000000      0.000000      87.000000       24.000000        7.000000      35.000000
50%    2024-07-01 00:00:00     12.000000   1799.560000    166.710000      0.000000    107.000000    167.980000     26.000000      7.000000      0.000000     159.000000       50.000000       12.000000      50.000000
75%    2024-09-30 00:00:00     15.000000   2961.340000    248.890000      0.000000    160.250000    253.352500     39.000000      9.000000      0.000000     229.000000       75.000000       17.000000      65.000000
max    2024-12-30 00:00:00     32.000000  10292.400000    381.200000      1.000000    200.000000    381.200000     52.000000     12.000000      1.000000     300.000000      100.000000       21.000000      80.000000
std                    NaN      4.226451   1398.413197     95.518430      0.271168     56.160593     96.137679     15.047013      3.443998      0.349530      81.126128       29.136575        5.489628      17.712634

In [17]:
df.describe(include="object")

C:\Users\user\AppData\Local\Temp\ipykernel_5104\702825166.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include="object")

        sku_id   category subcategory launch_date  season promo_event
count    73000      73000       73000       73000   73000        1600
unique     200          4           1           1       4           1
top     SKU001  Furniture     General  2023-01-01  Spring    Festival
freq       365      20075       73000       73000   18400        1600

In [18]:
df.nunique()

date               365
sku_id             200
units_sold          33
revenue           6614
unit_price         397
promo_flag           2
category             4
subcategory          1
launch_date          1
unit_cost          125
list_price         200
week                52
month               12
season               4
is_holiday           2
promo_event          1
on_hand_units      281
on_order_units     101
lead_time_days      19
reorder_point       61
dtype: int64

In [19]:
numerical_columns = df.select_dtypes(include=["int64", "float64"]).columns

print(numerical_columns)

Index(['units_sold', 'revenue', 'unit_price', 'promo_flag', 'unit_cost', 'list_price', 'week', 'month', 'is_holiday', 'on_hand_units', 'on_order_units', 'lead_time_days', 'reorder_point'], dtype='str')

In [20]:
df.to_csv("../data/processed/cleaned_master_dataset.csv", index=False)

print("Cleaned dataset saved successfully.")

Cleaned dataset saved successfully.